In [1]:
"""
Group B: Assissgenment 2. Write a python program to illustrate ART neural network. 
"""


import numpy as np

class ART1:
    def __init__(self, input_size, num_categories, rho=0.5):
        self.rho = rho  # Vigilance parameter (controls category granularity)
        # Bottom-up weights: categories x input_size
        self.Wf = np.ones((num_categories, input_size), dtype=np.float32)
        # Top-down weights: input_size x categories
        self.Wb = np.ones((input_size, num_categories), dtype=np.float32)

    def match(self, x, j):
        """Compute the match between input x and category j's top-down weights."""
        return np.sum(np.minimum(x, self.Wb[:, j])) / np.sum(x)

    def train(self, data):
        for x in data:
            for j in range(self.Wf.shape[0]):
                if self.match(x, j) >= self.rho:
                    # Check if x is a subset of the top-down weights for category j
                    if np.all(x * self.Wb[:, j] == x):
                        # Update weights to the intersection (ART1 learning rule)
                        self.Wf[j] = np.minimum(self.Wf[j], x)
                        self.Wb[:, j] = self.Wf[j]
                        break  # Move to next pattern once a category is found

# Example usage
data = np.array([
    [1, 0, 0, 1],
    [1, 0, 0, 1],
    [0, 1, 1, 0],
    [0, 1, 1, 0]
])

art = ART1(input_size=4, num_categories=2, rho=0.8)
art.train(data)

print("Trained bottom-up weights:\n", art.Wf)
print("Trained top-down weights (transposed for clarity):\n", art.Wb.T)


Trained bottom-up weights:
 [[1. 0. 0. 1.]
 [0. 1. 1. 0.]]
Trained top-down weights (transposed for clarity):
 [[1. 0. 0. 1.]
 [0. 1. 1. 0.]]


In [1]:
"""
Group B: Assignment No. 2
Assignment Title: Write a python program to illustrate ART neural network.
"""

import numpy as np

# Define the ART1 class
class ART1:
    def __init__(self, input_size, num_categories, rho=0.5):
        self.rho = rho  # Vigilance parameter: controls how similar a pattern must be to fit a category

        # Bottom-up weights (category to input): Initialized to ones
        self.Wf = np.ones((num_categories, input_size), dtype=np.float32)

        # Top-down weights (input to category): Transpose of bottom-up
        self.Wb = np.ones((input_size, num_categories), dtype=np.float32)

    def match(self, x, j):
        """
        Calculate the match score between input x and category j
        using the top-down weights.
        """
        return np.sum(np.minimum(x, self.Wb[:, j])) / np.sum(x)

    def train(self, data):
        """
        Train the ART1 network using binary input data.
        """
        for x in data:
            for j in range(self.Wf.shape[0]):
                # Check if the match exceeds vigilance threshold
                if self.match(x, j) >= self.rho:
                    # Ensure x is a subset of the top-down weights
                    if np.all(x * self.Wb[:, j] == x):
                        # Update weights using ART1 learning rule (intersection)
                        self.Wf[j] = np.minimum(self.Wf[j], x)
                        self.Wb[:, j] = self.Wf[j]
                        break  # Once a category is assigned, move to next input

# Example binary input data
data = np.array([
    [1, 0, 0, 1],
    [1, 0, 0, 1],
    [0, 1, 1, 0],
    [0, 1, 1, 0]
])

# Create ART1 model
art = ART1(input_size=4, num_categories=2, rho=0.8)

# Train the model with input data
art.train(data)

# Print the trained weights
print("Trained bottom-up weights (Wf):")
print(art.Wf)

print("\nTrained top-down weights (Wb.T):")
print(art.Wb.T)


Trained bottom-up weights (Wf):
[[1. 0. 0. 1.]
 [0. 1. 1. 0.]]

Trained top-down weights (Wb.T):
[[1. 0. 0. 1.]
 [0. 1. 1. 0.]]
