In [1]:
""" 
Group B: Assignment No. 8
Assignment Title: Write a python program in python program for
creating a Back Propagation Feed-forward neural network
"""
import numpy as np

# Define sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define derivative of sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

# Define input dataset
X = np.array([[0,0], [0,1], [1,0], [1,1]])

# Define output dataset
y = np.array([[0], [1], [1], [0]])

# Define hyperparameters
learning_rate = 0.1
num_epochs = 100000

# Initialize weights randomly with mean 0
hidden_weights = 2*np.random.random((2,2)) - 1
output_weights = 2*np.random.random((2,1)) - 1

# Train the neural network
for i in range(num_epochs):
    # Forward propagation
    hidden_layer = sigmoid(np.dot(X, hidden_weights))
    output_layer = sigmoid(np.dot(hidden_layer, output_weights))
    # Backpropagation
    output_error = y - output_layer
    output_delta = output_error * sigmoid_derivative(output_layer)
    hidden_error = output_delta.dot(output_weights.T)
    hidden_delta = hidden_error * sigmoid_derivative(hidden_layer)
    output_weights += hidden_layer.T.dot(output_delta) * learning_rate
    hidden_weights += X.T.dot(hidden_delta) * learning_rate
    
# Display input and output
print("Input:")
print(X)
print("Output:")
print(output_layer)

Input:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Output:
[[0.44170525]
 [0.98449412]
 [0.38484524]
 [0.38543939]]


In [1]:
""" 
Group B: Assignment No. 8
Assignment Title: Write a Python program for creating a Back Propagation 
Feed-forward neural network
"""

import numpy as np  # Import NumPy library for working with arrays and math functions

# --- Activation Functions ---
def sigmoid(x):
    return 1 / (1 + np.exp(-x))  # Sigmoid function to convert values between 0 and 1

def sigmoid_derivative(x):
    return x * (1 - x)  # Derivative of sigmoid used in backpropagation to adjust weights

# --- XOR Dataset ---
X = np.array([[0, 0],   # Input data: two binary inputs
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[0],      # Expected output (XOR logic)
              [1],
              [1],
              [0]])

# --- Hyperparameters ---
learning_rate = 0.1       # Controls how much weights are changed in each step
num_epochs = 100000       # Number of training loops

# --- Weight Initialization ---
np.random.seed(42)        # Set seed for random values to get same result every time
hidden_weights = 2 * np.random.random((2, 2)) - 1  # Weights between input and hidden layer
output_weights = 2 * np.random.random((2, 1)) - 1  # Weights between hidden and output layer

# --- Training ---
for i in range(num_epochs):  # Repeat training for given number of times
    # --- Forward pass ---
    hidden_layer = sigmoid(np.dot(X, hidden_weights))  # Calculate values at hidden layer
    output_layer = sigmoid(np.dot(hidden_layer, output_weights))  # Calculate values at output layer
    
    # --- Backward pass ---
    output_error = y - output_layer           # Find error (difference between expected and predicted)
    output_delta = output_error * sigmoid_derivative(output_layer)  # Adjust output layer weights

    hidden_error = output_delta.dot(output_weights.T)  # Calculate error for hidden layer
    hidden_delta = hidden_error * sigmoid_derivative(hidden_layer)  # Adjust hidden layer weights

    # --- Update weights ---
    output_weights += hidden_layer.T.dot(output_delta) * learning_rate  # Update output weights
    hidden_weights += X.T.dot(hidden_delta) * learning_rate             # Update hidden weights

# --- Final Output ---
print("Input:")  # Show input data
print(X)

print("\nExpected Output:")  # Show target (expected) output
print(y)

print("\nPredicted Output:")  # Show what the model has learned (predicted values)
print(np.round(output_layer, 3))  # Round output for better readability


Input:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Expected Output:
[[0]
 [1]
 [1]
 [0]]

Predicted Output:
[[0.033]
 [0.93 ]
 [0.93 ]
 [0.093]]
